name: swaply
description: "Swaply 鈥?marketplace app"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 鈥斺€?涓庝綘鐜版湁浠ｇ爜鍖归厤銆佸湪 3.19.6 涓嬬ǔ瀹氱殑鐗堟湰 鈥斺€?
  supabase_flutter: 2.5.8
  shared_preferences: 2.2.3
  provider: 6.1.2
  flutter_screenutil: 5.9.0
  url_launcher: 6.3.1
  image_picker: 1.1.2
  photo_view: 0.14.0
  share_plus: 9.0.0
  app_links: 6.4.0
  package_info_plus: 7.0.0
  sign_in_with_apple: 5.0.0
  google_sign_in: 6.2.2
  http: 1.2.2
  flutter_local_notifications: 16.3.3
  timezone: 0.9.4
  intl: 0.18.1
  path_provider: 2.1.4
  uuid: 3.0.7
  file_picker: 8.0.5
  flutter_image_compress: 2.3.0
  rxdart: 0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  # 鍥哄畾鏃ч摼璺紝閬垮厤 iOS 榛戝睆
  flutter_native_splash: 2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/trending_items/
    - assets/images/trending_items/item1/
    - assets/images/trending_items/item2/
    - assets/images/trending_items/item3/
version: 1.0.0+1
